### PR TITLE
feat: proxy support for image sources

### PR DESCRIPTION
**Pull request by MaikoTan**

### CODE REVIEW

**Comment by SaarChaffee** [comment]
[E] booru source pixiv unknown error: get pixiv image failed: Error: Login failed with status code undefined undefined

**Comment by MaikoTan** [comment]
Uh?
image

**Comment by SaarChaffee** [comment]
[W] booru source konachan request failed with code 403 "<!DOCTYPE html><html lang=\"en-US\"><head><title>Just a moment...</title>......"

**Comment by SaarChaffee** [comment]
```log
2024-03-09 21:15:43 [D] booru Error: fetch https://capi-v2.sankakucomplex.composts/?tags=+order:random&limit=1 failed
                            at D:\Desktop\GitHub\BOT\koishi-app\node_modules\undios\lib\index.cjs:187:23
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async [cordis.invoke] (D:\Desktop\GitHub\BOT\koishi-app\node_modules\undios\lib\index.cjs:186:19)
                            at SankakuComplexImageSource.get (d:\Desktop\GitHub\BOT\koishi-app\external\booru\packages\sankaku\src\index.ts:21:22)
                            at Proxy.get (d:\Desktop\GitHub\BOT\koishi-app\external\booru\packages\core\src\index.ts:65:22)
                            at Command.<anonymous> (d:\Desktop\GitHub\BOT\koishi-app\external\booru\packages\core\src\command.tsx:29:22)
                            at Array.<anonymous> (D:\Desktop\GitHub\BOT\koishi-app\node_modules\@koishijs\core\src\command\command.ts:287:14)
                            at Command.execute (D:\Desktop\GitHub\BOT\koishi-app\node_modules\@koishijs\core\src\command\command.ts:303:22)
                            at <anonymous> (D:\Desktop\GitHub\BOT\koishi-app\node_modules\@koishijs\core\src\session.ts:396:22)
                            at Proxy.withScope (D:\Desktop\GitHub\BOT\koishi-app\node_modules\@koishijs\core\src\session.ts:293:22)
```

**Comment by SaarChaffee** [comment]
Yande get a long RT.

**Comment by MaikoTan** [comment]
Looks like we should use api key for requesting danbooru or sankaku instead of unauthorised requests.

**Review by SaarChaffee — APPROVED** [review]

**Pull request merged**
